services:
    wptwilioapp:
        restart: always
        build: wptwilioapp
        command: pipenv run python3 -u server_app.py
        volumes:
            - ./wptwilioapp:/app/
        ports:
            - 80:8080
volumes:
    wptwilioapp:
