services:
    whatgpt:
        container_name: whatgpt
        restart: always
        build: app
        command: pipenv run python3 -u server_app.py
        volumes:
            - ./app:/app/
        ports:
            - 80:8080
volumes:
    app:
